export const LOAD_EXERCISES_SUCCESS = 'LOAD_EXERCISES_SUCCESS';
export const INIT_STEP_SUCCESS = 'INIT_STEP_SUCCESS';
export const NEXT_STEP_SUCCESS = 'NEXT_STEP_SUCCESS';
export const PREVIOUS_STEP_SUCCESS = 'PREVIOUS_STEP_SUCCESS';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
